version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "11:30"
      timezone: "UTC"
    target-branch: master
    reviewers:
      - mohnoor94
    labels:
      - Dependabot
