baseURL: "https://www.noor.guru"
title: noor.guru
paginate: 7
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
#        - name: System Design
#          url: categories/system-design/
#          weight: 1
#        - name: Java
#          url: categories/java/
#          weight: 4
#        - name: Scala
#          url: categories/scala/
#          weight: 5
#        - name: Python
#          url: categories/python/
#          weight: 2
#        - name: C++
#          url: categories/c++/
#          weight: 3
#        - name: Matlab
#          url: categories/matlab/
#          weight: 6
        - name: Search
          url: search
          weight: 10
        - name: Home
          url: /
          weight: 100

      footer:
        - name: Categories
          url: categories
          weight: 1
        - name: Tags
          url: tags
          weight: 2
        - name: Archive
          url: archive
          weight: 3
        - name: Search
          url: search
          weight: 4
        - name: My Apps
          url: https://go.noor.guru/apps
        - name: My CV
          url: https://go.noor.guru/cv


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Programming and Technology Guru!"
  author: Noor
  hideSummary: true
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  #  comments: true
  # images: ["papermod-cover.png"]
  #  editPost:
  #    URL: "https://github.com/mohnoor94/NoorGuru/blob/master/content"
  #    Text: "Suggest Changes"
  #    appendFilePath: true

  profileMode:
    enabled: false
    title: noor.guru
    imageUrl: "images/logo.svg"
    imageTitle: noor.guru logo
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: Java
        url: categories/java
      - name: Scala
        url: categories/scala
      - name: Python
        url: categories/python
      - name: C++
        url: categories/c++
      #      - name: Blog
      #        url: posts
      - name: Archive
        url: archive
      #      - name: Categories
      #        url: categories
      - name: Tags
        url: tags
      - name: Search
        url: search


  homeInfoParams:
    Title: "noor.guru"
    video_series:
      - name: C++ for Beginners
        url: /series/c++-for-beginners/
      - name: Complete Python Masterclass
        url: /series/complete-python-masterclass/
      - name: Matlab Lectures
        url: /series/matlab-lectures/

    series:
      - name: Scalability
        url: /series/scalability/
      - name: Solid Design Principles
        url: /series/solid-design-principles/
      - name: Java Best Practices
        url: /series/java-best-practices/

    categories:
      - name: System Design
        url: categories/system-design/
      - name: Java
        url: categories/java
      - name: Scala
        url: categories/scala
      - name: Python
        url: categories/python
      - name: C++
        url: categories/c++
      - name: Matlab
        url: categories/matlab

    resources:
      - name: C++ Study Materials
        url: cpp-resources
      - name: Technical Interview Preparation Guide
        url: technical-interview-preparation-guide

    Content: >
      Welcome to my cyber home.


      Here, I share my knowledge so it may help somebody out there (maybe you?).


  socialIcons:
    - name: github
      url: "https://go.noor.guru/github"
    - name: linkedin
      url: "https://go.noor.guru/linkedin"
    - name: youtube
      url: "https://go.noor.guru/youtube"
    #    - name: youtube
    #      url: "https://go.noor.guru/youtube-cwn"
    - name: stackoverflow
      url: "https://go.noor.guru/sof"
    - name: twitter
      url: "https://go.noor.guru/twitter"
    - name: email
      url: "https://go.noor.guru/email"
  #    - name: KoFi
  #      url: "https://ko-fi.com/adityatelange"
  #    - name: RsS
  #      url: "index.xml"

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: "G-XHXB3G7XDR"

  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"
    disableHLJS: true

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
     highlight:
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: dracula
#        style: monokai
#        style: native

       #noClasses: true

# styles: https://xyproto.github.io/splash/docs/all.html

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true