baseURL: https://www.noor.guru
languageCode: en-us
defaultContentLanguage: en
title: noor.guru
theme: cupper-hugo-theme
# googleAnalytics: UA-123456789-1
# disqusShortname: yourdiscussshortname
# enableGitInfo: true

taxonomies:
  tag: tags
  course: courses

permalinks:
  post: /post/:slug
  cpp:  /:sections/:slug

imaging:
  quality: 99

params:
  # description: An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project.
  # homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  # footer: 2014-2021 | 'Mohammad Noor' AbuKhleif [@moh_noor94](https://twitter.com/moh_noor94)
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  # codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  moveFooterToHeader: false
  customCss:
    - css/nav.css
  # customJs:
    # - js/custom_01.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: C++ Course
      url: /cpp
      weight: 4
    # - name: About
    #   url: /about/
    #   weight: 4
    # - name: RSS
    #   url: /index.xml
    #   weight: 5

# markup:
#   defaultMarkdownHandler: goldmark
#   goldmark:
#     extensions:
#       definitionList: true
#       footnote: true
#       linkify: true
#       strikethrough: true
#       table: true
#       taskList: true
#       typographer: true
#     parser:
#       attribute: true
#       autoHeadingID: true
#     renderer:
#       hardWraps: false
#       unsafe: true
#       xHTML: false
#   highlight:
#     codeFences: false
#     hl_Lines: ""
#     lineNoStart: 1
#     lineNos: false
#     lineNumbersInTable: true
#     noClasses: true
#     style: monokai
#     tabWidth: 4
#   tableOfContents:
#     endLevel: 6
#     startLevel: 2